adminUser:
  password: vault:jx-aps-consumer-plm3/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-consumer-plm3:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-consumer-plm3:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: PIPELINE_GITHUB_EMAIL
  token: vault:jx-aps-consumer-plm3/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: vault:jx-aps-consumer-plm3/prow:hmacToken
